apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
spec:
  isCA: true
  duration: 24h # 90d 2160h
  renewBefore: 3h # 7d 168h
  commonName: elasticsearch
  secretName: selfsigned-cert-tls
  issuerRef:
    name: selfsigned-issuer
